### ISSUE TITLE
Flash message use in Mustache, how ?

### ISSUE THREAD

**Issue by Sulla** [codeguy/Slim-Extras#12]
How i can get flash message from this structure: 

Array
(
    [flash] => Slim_Session_Flash Object
        (
            [sessionKey:protected] => flash
            [messages:protected] => Array
                (
                    [prev] => Array
                        (
                        )

```
                [next] => Array
                    (
                    )

                [now] => Array
                    (
                        [error] => User email is required
                    )

            )

    )

[name] => gregory
```

)

**Comment by codeguy** [comment]
The `Slim_Middleware_Flash` instance implements the `ArrayAccess` interface. Within your View, consider the `flash` variable to be an associative array. The flash instance is automatically set as a View variable when you instantiate Slim. You can usually access the Flash variable as `flash` based on your given View's syntax. Given:

```
$app->get('/foo', function () {
    $app->flashNow('info', 'This is a flash message');
    $app->render('foo.mustache');
});
```

The View template would be something like:

```
{{#flash}}{{info}}{{/flash}}
```

That's really verbose. I believe you can enable dot-syntax by adding this pragma statement at the top of your Mustache template:

```
{{%DOT-NOTATION}}
```

And then use:

```
{{flash.info}}
```

I'm basing this information on what I've read here: https://github.com/bobthecow/mustache.php/issues/34

If you have any further questions that are not immediate bugs with the framework, please post them to http://help.slimframework.com.

Hope this helps!
Josh

**Comment by gustavnikolaj** [comment]
I found this page when I googled for an solution, and even though the solution is available at the slimframework forums I think that it is worth adding here.

When using dot-notation the flash messages is not available at `{{flash.key}}` as codeguy suggests above, but in `{{flash.getMessages.key}}`.

**Comment by codeguy** [comment]
@gustavnikolaj The Flash object implements the ArrayAccess interface. My syntax may be off, but it should only require `flash.key` (or however you use array-access in Mustache). You should not need to use the `getMessages` function on the Flash object.

**Comment by gustavnikolaj** [comment]
Thank you for the quick reaction. I am sure that you are right in theory, but I just have had no luck trying to get it to work.

No matter how i try to get around it I always end up with no luck trying to get it to work the way that you describe. I think it may be a flaw in the implementation of either Mustache.php or the SlimExtras-MustacheView.

I dont know if making a test-case would make it any easier for you, as I havent made any customizations in the environment where I use it. If it would be of any use to you I'll make it right away.

It's Slim v.1.5.0, Mustache.php v.1.1.0 (Spec. v.1.1.2) and the SlimMustacheView is just pulled off github today.

**Comment by bondarewicz** [comment]
Was this ever resolved ? I have a same issue :

[slim.flash] => Slim\Middleware\Flash Object
                        (
                            [settings:protected] => Array
                                (
                                    [key] => slim.flash
                                )

```
                        [messages:protected] => Array
                            (
                                [prev] => Array
                                    (
                                    )

                                [next] => Array
                                    (
                                    )

                                [now] => Array
                                    (
                                        [error] => Authentication failed
                                    )

                            )

                        [app:protected] => Slim\Slim Object
```

 _RECURSION_
                            [next:protected] => Slim\Slim Object
 _RECURSION_
                        )
then using mustache trying to output:

{{#flash}}{{error}}{{/flash}}

does not render anything....

**Comment by dhilowitz** [comment]
Thanks @gustavnikolaj! I found that I also had to use {{{flash.getMessages.error}}} in order to get my flash error messages.

**Comment by codeguy** [comment]
For the next major version, instead of passing the actual Flash object to the template, I'll just pass the array of applicable messages which should solve this problem.
