### ISSUE TITLE
Error when loading in shared hosting

### ISSUE THREAD

**Issue by codecowboy** [codeguy/Slim-Extras#13]
I am getting this error when trying to use the Twig extension on shared hosting (phpfog):

Fatal error: Class 'Twig_Loader_Filesystem' not found in /var/fog/apps/app29725/fb-sandbox.phpfogapp.com/Views/TwigView.php on line 91

I have confirmed that the file is on disk at /vendor/twig/Loader/Filesystem.php

It works fine locally.

This is what I have in index.php:

```require 'Slim/Slim.php';
//require_once 'vendor/.composer/autoload.php';
require_once 'Views/TwigView.php';
//require_once 'vendor/twig/Loader/Filesystem.php';

require_once 'vendor/facebook/src/facebook.php';

TwigView::$twigDirectory = **DIR** . '/vendor/twig';

TwigView::$twigExtensions = array(
    'Twig_Extensions_Slim',
);```

**Comment by silentworks** [comment]
can you make sure that the twigDirectory exists on your server by user. Inside your TwigView try var_dumping

```
self::$twigDirectory
```

in the getEnvironment function.

**Comment by silentworks** [comment]
Sorry I closed this by mistake, now reopened.

**Comment by codecowboy** [comment]
I _think_ this was caused by a combination of composer, git and tower. I had a duplicate copy of twig which was confusing things. It seems to be working now. Thanks for getting back to me.

This fixed it in the end :TwigView::$twigDirectory = **DIR** . '/vendor/twig/twig/lib/Twig'; - this is the path that composer installed twig to.

**Comment by silentworks** [comment]
why not just use the composer Autoloader? I have a setup using that at the moment and it works great since the TwigView extension check to see if Twig is already autoloaded.
