### ISSUE TITLE
Error 505 when using Timestamp Logfile Writer

### ISSUE THREAD

**Issue by hexa2k9** [codeguy/Slim-Extras#15]
I'm seing some errors on my Webserver Logs in case of Application Errors:
2012/04/28 21:12:04 [error] 2308#0: *24 FastCGI sent in stderr: "PHP Fatal error:  Undefined class constant 'FATAL' in /Users/hexa/Code/api-v2.slim/vendor/SlimLogfileWriter.class.php on line 103" while reading response header from upstream, client: 10.100.6.17, server: apidev.iz-smart.net, request: "GET /info/ HTTP/1.1", upstream: "fastcgi://unix:tmp/fcgi_php.sock:", host: "apidev.iz-smart.net:8080"

I'm on Slims current `master` branch.

**Comment by codeguy** [comment]
Yep, only use that with the `release-1.6.3` branch for now. It'll work fine when I take 1.6.3 into the stable master branch.
