### ISSUE TITLE
Make TwigView::getEnvironment public

### ISSUE THREAD

**Issue by codeguy** [codeguy/Slim-Extras#2]
Make TwigView::getEnvironment public to allow easier customization of the Twig environment.

**Comment by ckailash** [comment]
Any luck with this one? Lots of useful stuff can be done if this is completed

**Comment by techdubb** [comment]
This one was done in this pull request.

https://github.com/codeguy/Slim-Extras/pull/4

**Comment by codeguy** [comment]
Yep. Closing out.
