### ISSUE TITLE
Composer Package not up to date / Autoloading and Require error

### ISSUE THREAD

**Issue by electricBonfire** [codeguy/Slim-Extras#30]
I have added slim/extras to my composer.json. It is currently downloading 1.0.2. This package is missing the middlewares. When I try to create a new TwigView It says it cannot find the class. If I manually require the TwigView.php file I get:  Class 'Slim_View' not found. I realize this is probably not an issue as much as it is my error in setting up the project. Can someone please help? Thanks, Shawn!

**Comment by silentworks** [comment]
What version of Slim are you using?
