### ISSUE TITLE
Multiple usernames and passwords for HttpDigestAuth?

### ISSUE THREAD

**Issue by arbet** [codeguy/Slim-Extras#37]
I'm trying to use multiple usernames and passwords with the HttpDigestAuth class, and it's not allowing me. 

`$app->add(new HttpDigestAuth('test', 'test'));
$app->add(new HttpDigestAuth('bla', 'bla'));`

I suspect that I'm adding two middleware classes, so it's asking for two authentications instead of one. Doesn't this class support multiple usernames and passwords?

**Comment by codeguy** [comment]
It does not. But this is a great idea for a new feature. If you have time to send a pull request that'd be great, else I can get around to this in the next week or so.

**Comment by codeguy** [comment]
Saw your pull request. Andrew or I will get that pulled in shortly.

**Comment by silentworks** [comment]
One of us need to test it out before merging it, I merged some pull requests in the past without testing them and they were not working in the end.

**Comment by arbet** [comment]
No problem. If you require any changes let me know.
