### ISSUE TITLE
Slim-Extras / Views / Rain.php Can't find class raintpl

### ISSUE THREAD

**Issue by boypt** [codeguy/Slim-Extras#45]
I'm on PHP 5.4.8, the Rain.php is reporting critical can't find class raintpl on line 96.

Line 96 97 should be:

```
        \raintpl::$tpl_dir = self::$rainTemplatesDirectory;
        \raintpl::$cache_dir = self::$rainCacheDirectory;
```

**Comment by silentworks** [comment]
Unfortunately I don't use Rain templating system, you might want to send a pull request and I will get this merged in.
