### ISSUE TITLE
Fix for Apache HTTP_AUTH with PHP/CGI

### ISSUE THREAD

**Issue by crypto-scythe** [codeguy/Slim-Extras#49]
Hi there,

I made a fix so that HttpAuthBasic and HttpAuthDigest work with PHP/CGI on Apache

put in the index.php before instantiating Slim Framwork:

if ( isset( $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] ) ) {
  if ( strpos( $_SERVER['REDIRECT_HTTP_AUTHORIZATION'], 'Basic' ) == 0 ) {
    list( $_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW'] ) = explode( ':' , base64_decode( substr( $_SERVER['REDIRECT_HTTP_AUTHORIZATION'], 6) ) );
  }
  if( strpos( $_SERVER['REDIRECT_HTTP_AUTHORIZATION'], 'Digest' ) == 0 ) { 
    $_SERVER['PHP_AUTH_DIGEST'] = substr( $_SERVER['REDIRECT_HTTP_AUTHORIZATION'], 7);
  } 
}

And in .htaccess after RewriteBase:

RewriteRule .\* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

That worked for me on two different webhosters ( domainfactory and 1und1 )

**Comment by silentworks** [comment]
Thanks for the tip.
