### ISSUE TITLE
StrongAuth: Where is the \Strong\Strong class?

### ISSUE THREAD

**Issue by mike-rsi** [codeguy/Slim-Extras#56]
A key component of the StrongAuth middleware seems to be the \Strong\Strong class, but I can't find it in the code-base or even referenced anywhere in the documentation.  Where could one acquire this class, or are we supposed to create our own?  Thanks.

**Comment by mike-rsi** [comment]
I think I found the repo that contains the Strong class that StrongAuth requires:
https://github.com/silentworks/Strong

Perhaps this should be noted in the documentation?

**Comment by silentworks** [comment]
Good Idea, I shall add that in.

**Comment by kieranajp** [comment]
This Strong class doesn't seem to be installable with composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package slim/strong could not be found in any version, there may be a typo in the package name.
```

Do we have to install this manually now?

**Comment by silentworks** [comment]
No that shouldn't be the case. Maybe Composer is having problems with Github api again. Can you post your composer.json file also.

**Comment by kieranajp** [comment]
Sure

```
{
    "require" : {
        "slim/slim" : "2.*",
        "twig/twig" : "1.*",
        "slim/extras" : "*",
    "slim/strong" : "*"
    }
}
```

**Comment by silentworks** [comment]
Try

``` json
{
    "require" : {
        "slim/slim" : "2.2.*",
        "twig/twig" : "1.*",
        "slim/extras" : "dev-master",
        "slim/strong" : "dev-develop"
    }
}
```

**Comment by kieranajp** [comment]
While Strong's documentation does say "*", that seemed to do the trick. Thank you.

**Comment by silentworks** [comment]
Sorry I will update the docs soon, along with some new features added to Strong. I have been really busy at work.

**Comment by kieranajp** [comment]
No problem, thanks again for taking the time to help
