### ISSUE TITLE
JSONP Middleware class fails to load.

### ISSUE THREAD

**Issue by gregnorth** [codeguy/Slim-Extras#78]
Following the simple method to add the middleware described in the classes comments presents a fatal error.

"Fatal error: Call to undefined function Slim\Extras\Middleware\JSONPMiddleware()"

**Comment by keithmorris** [comment]
It looks like this has to do with an improperly named file for composer autoloading. The file should not be named `Jsonp.php` but rather `JSONPMiddleware.php`

**Comment by mastermindg** [comment]
Just installed a new project using Composer and I can confirm that the filename discrepency is still an issue. This is preventing adding this middleware. I forked and created a pull request for this update.

**Comment by henrik-m** [comment]
I stumbled upon this too. This issue is now 2 years old. Is this repository still maintained?

**Comment by silentworks** [comment]
No this repository is not maintained at all.
