### ISSUE TITLE
New home for log writers?

### ISSUE THREAD

**Issue by tuupola** [codeguy/Slim-Extras#84]
Readme says this repository is deprecated. What is current repository for log writers etc?

**Comment by codeguy** [comment]
Logging will be removed from version 3.0, as the framework itself does not rely on any form of logging internally. That  being said, this repo won't be disappearing, so you can certainly continue referencing it in your composer manifests or downloading its files manually for your apps. It will soon become easier to discover third-party Slim addons like custom loggers, etc. More info on that soon.

**Comment by tuupola** [comment]
Is there any suggested naming scheme for third party addons?  For example if I made a FooBar middleware should I call it `\Slim\Middleware\FooBar` or something else?

**Comment by silentworks** [comment]
I would suggest creating your own namespace for your middlewares, It would be better to leave the Slim\Middleware namespace reserved for the core team and core addons. It would also make sense to keep your middleware namespace consistent across all middleware created by yourself.
