### ISSUE TITLE
Split this repository

### ISSUE THREAD

**Issue by DavidePastore** [codeguy/Slim-Extras#93]
You could split this and create SlimLog and SlimMiddleware and link them in the Readme. It's better to do now this kind of thing. I think that this is a micro task.

Please @codeguy and @silentworks.

**Comment by silentworks** [comment]
@DavidePastore we have a middleware repo, its just not populated with the content of this one as yet, I will talk with @codeguy and see if we can get it up to speed soon, You can follow the progress here https://github.com/codeguy/Slim-Middleware

**Comment by DavidePastore** [comment]
Ok @silentworks. This is a good news. I'm working on some loggers and I wish to include them in the official repo. I think that they can be useful.

**Comment by DavidePastore** [comment]
@codeguy  @silentworks Are there no updates?

**Comment by silentworks** [comment]
We are making a move on this now, thanks for the nudge. Will update you soon.

**Comment by silentworks** [comment]
The logger is now located here https://github.com/codeguy/Slim-Logger, you can also get this off packagist too.

**Comment by DavidePastore** [comment]
@silentworks Thanks! Please check #100 so developers know where to go.

**Comment by silentworks** [comment]
Thats now merged.

**Comment by DavidePastore** [comment]
@silentworks  Thanks.
